import contractor from '../app/(drawer)/(tabs)/(contractor)';

export default Object.freeze({
  appName: 'NexaBind',
  welcomeTo: 'Welcome to',
  nexa: 'Nexa',
  bind: 'Bind',
  welcomeScreenSubText:
    'Connect directly with skilled local contractors ready to bring their expertise and reliability to your doorstep.',
  skipButton: 'Skip for now',
  logIn: 'Log In',
  signIn: 'Sign In',
  signUp: 'Sign Up',
  signOut: 'Sign Out',
  signInWithGoogle: 'Sign In with Google',
  signUpSubText: 'Create your account with this information',
  name: 'Name',
  email: 'Email',
  password: 'Password',
  confirmPassword: 'Confirm Password',
  placeName: 'Your name',
  placeEmail: 'Your@example.com',
  nameError: 'Name must be more than 3 chars',
  emailError: 'Invalid email format',
  passwordError:
    'Must be at least 8 characters long | Must contain an uppercase letter (A-Z) | Must contain a lowercase letter (a-z) | Must contain a digit (0-9) | Must contain a special character (@$!%*?&)',
  confirmPasswordError: 'Password and Confirm Password must match',
  alreadyHaveAnAccount: 'Already have an account?',
  signInNow: 'Sign In Now',
  bySignedIn: 'By Signing Up you are agreeing to our',
  termsText: 'Terms of Service & Privacy Policy',
  yourSkills: 'Your Skills',
  selectSkills: 'Select skills',
  noSkillsMsg: 'Oops!! No Skills Available!!',
  searchForSkillsMsg: 'Please search for the skill',
  location: 'Location',
  searchAddress: 'Search Address',
  hey: 'Hey',
  weAreAlmostDone: 'We are almost done!',
  fillUpProfileText: 'Fill up the Information below to create your profile',
  signUpAs: 'Sign Up as',
  selectUserType: 'Select User Type',
  userTypeError: 'You must select a user type.',
  noSkillError: 'You must select at least 1 skill.',
  addressError: 'You must provide address.',
  aboutYou: 'About you',
  tellUsAboutYou: 'Tell us about yourself',
  emailVerification: 'Email Verification',
  iconNotFound: 'Icon not found',
  emailVerifySuccesss: 'Email Verification successful',
  emailVerificationSent: 'Email Verification sent to your email. Please check your email.',
  verificationSend: ' Verification Send',
  weHaveSentText: `We've sent a verification email to`,
  checkEmailText:
    'Please check your mail and confirm. We need to verification to complete your registration.',
  didNotReceiveText: 'If you did not receive the email,',
  resendBtnText: 'Resend Confirmation Email',
  goHome: 'Go Home',
  forgotPass: 'Forgot Password',
  proceed: 'Proceed',
  enterEmail: 'Enter your email',
  newPassword: 'Enter New Password',
  setItNow: 'Set it Now',
  enableLocation: 'Enable Location',
  profile: 'Profile',
  about: 'About',
  less: 'Less',
  more: 'More',
  read: 'Read',
  skills: 'Skills',
  licenses: 'Licenses',
  reviews: 'Reviews',
  save: 'Save',
  userBioError: 'About you must be more than 5 characters',
  area: 'Area',
  areaRadiusErrorText: 'Radius must be between 5KM and 200KM.',
  contractorType: 'Contractor Type',
  searchForContractors: 'Search for contractor',
  locationRequired: 'Location Permission Required',
  enhanceText: `To enhance your experience and provide personalized services, we'd like to access your location data.`,
  whycollectText: 'Why we collect your location:',
  trilorText: '-Tailor content, services, and offers specific to your region.',
  provideText: '- Provide location-based assistance or recommendations.',
  improveText: `- Improve our website's functionality and your user experience.`,
  privercyText: 'Your privacy matters:',
  locationDataText:
    'Your location data is collected and stored securely. We do not share this information with third parties without your consent, and you can withdraw your permission at any time in the settings.',
  readLess: 'Read Less',
  readMore: 'Read More',
  no: 'No',
  found: 'found!',
  changeSearchCriteria: 'Please change your search criteria',
  apply: 'Apply',
  cancel: 'Cancel',
  filters: 'Filters',
  contractor: 'Contractor',
  client: 'Client',
  contractorsFound: 'Contractors Found',
  forgotPassword: 'Forgot your password',
  enterEmailBelow: `Enter your email below and we will send you a link to reset your password. If you can't find the email check your spam folder.`,
  googleEmailWarning: 'Please note that if you signed up using Google this form will not work.',
  updateProfileImage: 'Update Profile Picture',
  licenseDeleted: 'License deleted successfully!',
  licenseError: 'License Name is required',
  licenseName: 'Certificate & License Name',
  licensePlace: 'License Name',
  media: 'Media',
  upload: 'Upload',
  licenseImageError: 'Upload an Image!!',
  licenseAdded: 'License added successfully!',
  logOut: 'Log out',
  messages: 'Messages',
  yourJobs: 'Your Jobs',
  darkMode: 'Dark Mode',
  km: 'Km',
  setNewPass: 'Set Your New Password',
  passResetSuccess: 'Password reset successful.',
  passResetMsg: 'Password reset request sent to your email. Please check your email.',
  enterCredentials: 'Enter your Credential to access your account',
  newAtNexaBind: 'New at Nexabind',
  signUpNow: 'Sign Up now',
  imageUploadFailed: 'Image failed to upload!!',
  profileUpdated: 'Profile updated successfully!',
  qrCode: 'Qr Code',
  settings: 'Settings',
  qrGenerateFailed: 'Failed to generate QR Image',
  qrSaveImageSuccess: 'QR Image is Successfully saved',
  quickLinkMessage: 'Quick Link to the Contractor Profile',
  shareQR: 'Share QR Code',
  saveQR: 'Save as Image',
  profileQrCode: 'Profile QR Code',
  scanQRCode: 'Scan this QR code',
  printQRCode: 'Print and stick it in your truck, sign boards, shop window and etc.',
  fileAccessDenied: '*Please Grant Access Permission to save or share this image',
  addLicenseLabel: 'Add Licenses / Certification',
  licensesLabel: 'Licenses / Certificates',
  searchSkills: 'Search Skills',
  getStart: 'Get Start',
});
