export default Object.freeze({
  appName: 'NexaBind',
  welcomeTo: 'Welcome to',
  nexa: 'Nexa',
  bind: 'Bind',
  welcomeScreenSubText:
    'Connect directly with skilled local contractors ready to bring their expertise and reliability to your doorstep.',
  skipButton: 'Skip for now',
  logIn: 'Log In',
  signIn: 'Sign In',
  signUp: 'Sign Up',
  signOut: 'Sign Out',
  signInWithGoogle: 'Sign In with Google',
  signUpSubText: 'Create your account with this information',
  name: 'Name',
  email: 'Email',
  password: 'Password',
  confirmPassword: 'Confirm Password',
  placeName: 'Your name',
  placeEmail: 'Your@example.com',
  nameError: 'Name must be more than 3 chars',
  emailError: 'Invalid email format',
  passwordError:
    'Must be at least 8 characters long | Must contain an uppercase letter (A-Z) | Must contain a lowercase letter (a-z) | Must contain a digit (0-9) | Must contain a special character (@$!%*?&)',
  confirmPasswordError: 'Password and Confirm Password must match',
  alreadyHaveAnAccount: 'Already have an account?',
  signInNow: 'Sign In Now',
  bySignedIn: 'By Signing Up you are agreeing to our',
  termsText: 'Terms of Service & Privacy Policy',
  yourSkills: 'Your Skills',
  selectSkills: 'Select skills',
  noSkillsMsg: 'Oops!! No Skills Available!!',
  searchForSkillsMsg: 'Please search for the skill',
  location: 'Location',
  searchAddress: 'Search Address',
  hey: 'Hey',
  weAreAlmostDone: 'We are almost done!',
  fillUpProfileText: 'Fill up the Information below to create your profile',
  signUpAs: 'Sign Up as',
  selectUserType: 'Select User Type',
  userTypeError: 'You must select a user type.',
  noSkillError: 'You must select at least 1 skill.',
  addressError: 'You must provide address.',
  aboutYou: 'About you',
  tellUsAboutYou: 'Tell us about yourself',
  emailVerification: 'Email Verification',
  iconNotFound: 'Icon not found',
  emailVerifySuccesss: 'Email Verification successful',
  emailVerificationSent: 'Email Verification sent to your email. Please check your email.',
  verificationSend: ' Verification Send',
  weHaveSentText: `We've sent a verification email to`,
  checkEmailText: 'Click the button in your email to verify your account.',
  didNotReceiveText: `If you can't find the email check your spam folder or,`,
  resendBtnText: 'Resend Confirmation Email',
  goHome: 'Go Home',
  forgotPass: 'Forgot Password',
  proceed: 'Proceed',
  enterEmail: 'Enter your email',
  newPassword: 'Enter New Password',
  setItNow: 'Set it Now',
  enableLocation: 'Enable Location',
  profile: 'Profile',
  about: 'About',
  less: 'Less',
  more: 'More',
  read: 'Read',
  skills: 'Skills',
  licenses: 'Licenses',
  reviews: 'Reviews',
  save: 'Save',
  userBioError: 'About you must be more than 5 characters',
  area: 'Area',
  areaRadiusErrorText: 'Radius must be between 5KM and 200KM.',
  contractorType: 'Contractor Type',
  searchForContractors: 'Search for contractors',
  locationRequired: 'Location Permission Required',
  enhanceText: `To enhance your experience and provide personalized services, we'd like to access your location data.`,
  whycollectText: 'Why we collect your location:',
  trilorText: '-Tailor content, services, and offers specific to your region.',
  provideText: '- Provide location-based assistance or recommendations.',
  improveText: `- Improve our website's functionality and your user experience.`,
  privercyText: 'Your privacy matters:',
  locationDataText:
    'Your location data is collected and stored securely. We do not share this information with third parties without your consent, and you can withdraw your permission at any time in the settings.',
  readLess: 'Read Less',
  readMore: 'Read More',
  yes: 'Yes',
  no: 'No',
  found: 'found!',
  changeSearchCriteria: 'Please change your search criteria',
  apply: 'Apply',
  cancel: 'Cancel',
  filters: 'Filters',
  contractor: 'Contractor',
  client: 'Client',
  contractorsFound: 'Contractors Found',
  forgotPassword: 'Forgot your password',
  enterEmailBelow: `Enter your email below and we will send you a link to reset your password. If you can't find the email check your spam folder.`,
  googleEmailWarning: 'Please note that if you signed up using Google this form will not work.',
  updateProfileImage: 'Update Profile Picture',
  licenseDeleted: 'License deleted successfully!',
  licenseError: 'License Name is required',
  licenseName: 'Certificate & License Name',
  licensePlace: 'License Name',
  media: 'Media',
  upload: 'Upload',
  licenseImageError: 'Upload an Image!!',
  licenseAdded: 'License added successfully!',
  licenseFailed: 'Failed to add license!!',
  logOut: 'Log out',
  messages: 'Messages',
  yourJobs: 'Your Jobs',
  darkMode: 'Dark Mode',
  km: 'Km',
  setNewPass: 'Set Your New Password',
  passResetSuccess: 'Password reset successful.',
  passResetMsg: 'Password reset request sent to your email. Please check your email.',
  enterCredentials: 'Enter your Credential to access your account',
  newAtNexaBind: 'New at Nexabind',
  signUpNow: 'Sign Up now',
  imageUploadFailed: 'Image failed to upload!!',
  profileUpdated: 'Profile updated successfully!',
  qrCode: 'Qr Code',
  settings: 'Settings',
  qrGenerateFailed: 'Failed to generate QR Image',
  qrSaveImageSuccess: 'QR Image is Successfully saved',
  quickLinkMessage: 'Quick Link to the Contractor Profile',
  shareQR: 'Share QR Code',
  saveQR: 'Save as Image',
  profileQrCode: 'Profile QR Code',
  scanQRCode: 'Scan this QR code',
  printQRCode: 'Print and stick it in your truck, sign boards, shop window and etc.',
  fileAccessDenied: '*Please Grant Access Permission to save or share this image',
  addLicenseLabel: 'Add Licenses / Certification',
  licensesLabel: 'Licenses / Certificates',
  searchSkills: 'Search Skills',
  getStart: 'Get Start',
  profileUpdateFailed: 'Failed to update the profile!!',
  postJob: 'Post Job',
  jobTitleText: 'Write a title for your job post',
  jobTitlePlace: 'Seeking Experienced Contractor for Comprehensive Home Renovation Project',
  addSkillsJobPost: 'Search or add up to 10 skills required',
  projectTimeline: 'Project Timeline',
  seleDate: 'Select a date',
  seleProjectBudget: 'Select Project Budget',
  fixedBudget: 'Fixed Budget',
  hourlyRate: 'Hourly Rate',
  enterBudget: 'Enter budget',
  from: 'From',
  to: 'To',
  maxHours: 'Max Hours',
  dollar: '$',
  perHour: '/hour',
  projectDetails: 'Project Details',
  uploadImage: 'Press to select & upload an image',
  imageSubText: 'Minimum 1600px width recommended. Max 10MB each',
  postJobLogInMsg: 'Please Log In to Post a Job',
  postJobSuccessMsg: 'Job Posted Successfully',
  jobSaveDraftMsg: 'We saved a draft',
  jobs: 'Jobs',
  radius: 'Radius',
  projectType: 'Project Type',
  dayPosted: 'Day Posted',
  priceRange: 'Price Range',
  priceRangeError: 'Price range must be valid and start value must be greater than 10',
  jobDetails: 'Job Details',
  jobsFound: 'Jobs Found',
  jobList: 'Job List',
  jobDeleted: 'Job deleted successfully.',
  draftLoaded: 'Draft loaded, continue editing to complete this draft.',
  yourBids: 'Your Bids',
  jobDesc: 'Job description',
  jobImages: 'Job Images',
  jobPosted: 'Posted Date',
  startDate: 'Start Date',
  endDate: 'End Date',
  skillsRequired: 'Skills Required',
  jobStatus: 'Job Status',
  searchForProjects: 'Search for jobs',
  searchTextEmpty: 'Search text is empty',
  switchToClient: 'Switch to Client',
  switchToContractor: 'Switch to Contractor',
  becomeContractor: 'Become a Contractor',
  verifyEmail: 'Verify Email',
  fillAllFields: 'Fill all required fields!!',
  writeReview: 'Write a Review',
  bidThisJob: 'Bid this Job',
  finishThisJob: 'Finish this Job',
  bid: 'Bid',
  submitBid: 'Submit Your Bid',
  bidQuote: 'Bid Quote',
  bidAmount: 'Bid Amount',
  wordLimit: 'Word limit 350',
  agreement: 'Agreement',
  agreeWithThis: 'I agree with this',
  bidPlaced: 'Bid placed successfully.',
  bidDetails: 'Bid Details',
  yourProposal: 'Your Proposal',
  contractorProposal: 'Contractor Proposal',
  bidInfo: 'Bid Info',
  commText: 'Communication with Contractor',
  acceptBidText: 'Do you want to accept this bid?',
  yesHire: 'Yes, Hire',
  notInterested: 'Not Interested',
  congratulations: 'Congratulations!',
  hiredMsg: 'You hired ',
  startConversation: 'Start conversation with ',
  okay: 'Okay',
  rejectBid: 'Reject Bid',
  seleReason: 'Select the reason of rejection',
  reasonPlaceholder: 'Describe the reason',
  submitNow: 'Submit Now',
  cancelGoBack: 'Cancel & Go Back to Bid',
  viewAllBids: 'View All Bids',
  bids: 'Bids',
  giveReview: 'Give Review',
  shareYourDetails: 'Share Your Details',
  reviewSuccess: 'Review successfully submitted.',
  reviewPlaceholder: 'Share your experience... What did you like or dislike?',
  reviewError: 'Please select a number of stars.',
  acceptBid: 'Accepted Bid',
  finishBidTxt: 'Do you want to complete this job?',
  bidMarkedComplete: 'This job will be marked as completed.',
  bidCompletedMsg: 'Job Completed Successfully.',
  jobCompletedMsg: 'Job Completed Successfully.',
  jobCompleted: 'Job Completed',
  notifications: 'Notifications',
  markAllRead: 'MARK ALL READ',
  portfolios: 'Portfolios',
  portfolioAdded: 'Portfolio added successfully!!',
  portfolioFailed: 'Failed to add portfolio!!',
  addPortfolio: 'Add Portfolio',
  title: 'Title',
  titlePlace: 'Enter title',
  portfolioNameError: 'Portfolio title is required',
  description: 'Description',
  tellUsAboutPortfolio: 'Tell us about portfolio',
  profileDescError: 'Portfolio description is required',
  portfolioImageError: 'Portfolio image is required',
  portfolioDeleted: 'Portfolio deleted successfully!!',
  nearByContractor: 'Nearby Contractors',
  welcomeScreenMessage: 'We are Binding you by connecting you with professionals.',
  landingScreenMessage:
    'Discover skilled local contractors in your vicinity who bring expertise and reliability to your doorstep',
});
