export default Object.freeze({
  appName: 'NexaBind',
  welcomeTo: 'Welcome to',
  nexa: 'Nexa',
  bind: 'Bind.',
  welcomeScreenSubText: 'Get Professional construction workers at any time',
  skipButton: 'Skip for now',
  logIn: 'Log In',
  signUp: 'Sign Up',
  signOut: 'Sign Out',
  signInWithGoogle: 'Sign In with Google',
  signUpSubText: 'Create your account with this information',
  name: 'Name',
  email: 'Email',
  password: 'Password',
  confirmPassword: 'Confirm Password',
  placeName: 'Your name',
  placeEmail: 'Your@example.com',
  nameError: 'Name must be more than 3 chars',
  emailError: 'Invalid email format',
  passwordError:
    'Must be at least 8 characters long | Must contain an uppercase letter (A-Z) | Must contain a lowercase letter (a-z) | Must contain a digit (0-9) | Must contain a special character (@$!%*?&)',
  confirmPasswordError: 'Password and Confirm Password must match',
  alreadyHaveAnAccount: 'Already have an account?',
  signInNow: 'Sign In Now',
  bySignedIn: 'By Signing up you are agreeing to our',
  termsText: 'Terms of Service & Privacy Policy',
  yourSkills: 'Your Skills',
  selectSkills: 'Select skills',
  noSkillsMsg: 'Oops!! No Skills Available!!',
  searchForSkillsMsg: 'Please search for the skill',
  location: 'Location',
  searchAddress: 'Search Address',
  hey: 'Hey',
  weAreAlmostDone: 'We are almost done!',
  fillUpProfileText: 'Fill up the Information below to create your profile',
  signUpAs: 'Sign Up as',
  selectUserType: 'Select User Type',
  userTypeError: 'You must select a user type.',
  noSkillError: 'You must select at least 1 skill.',
  addressError: 'You must provide address.',
  aboutYou: 'About you',
  tellUsAboutYou: 'Tell us about yourself',
  emailVerification: 'Email Verification',
  iconNotFound: 'Icon not found',
  emailVerifySuccesss: 'Email Verification successful',
  emailVerificationSent: 'Email Verification sent to your email. Please check your email.',
  verificationSend: ' Verification Send',
  weHaveSentText: `We've sent a verification email to`,
  checkEmailText:
    'Please check your mail and confirm. We need to verification to complete your registration.',
  didNotReceiveText: 'If you did not receive the email,',
  resendBtnText: 'Resend Confirmation Email',
  goHome: 'Go Home',
});
